// Code generated by "stringer -trimprefix=ControllerCommand_ -type=ControllerCommand"; DO NOT EDIT.

package goopenzwave

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ControllerCommand_None-0]
	_ = x[ControllerCommand_AddDevice-1]
	_ = x[ControllerCommand_CreateNewPrimary-2]
	_ = x[ControllerCommand_ReceiveConfiguration-3]
	_ = x[ControllerCommand_RemoveDevice-4]
	_ = x[ControllerCommand_RemoveFailedNode-5]
	_ = x[ControllerCommand_HasNodeFailed-6]
	_ = x[ControllerCommand_ReplaceFailedNode-7]
	_ = x[ControllerCommand_TransferPrimaryRole-8]
	_ = x[ControllerCommand_RequestNetworkUpdate-9]
	_ = x[ControllerCommand_RequestNodeNeighborUpdate-10]
	_ = x[ControllerCommand_AssignReturnRoute-11]
	_ = x[ControllerCommand_DeleteAllReturnRoutes-12]
	_ = x[ControllerCommand_SendNodeInformation-13]
	_ = x[ControllerCommand_ReplicationSend-14]
	_ = x[ControllerCommand_CreateButton-15]
	_ = x[ControllerCommand_DeleteButton-16]
}

const _ControllerCommand_name = "NoneAddDeviceCreateNewPrimaryReceiveConfigurationRemoveDeviceRemoveFailedNodeHasNodeFailedReplaceFailedNodeTransferPrimaryRoleRequestNetworkUpdateRequestNodeNeighborUpdateAssignReturnRouteDeleteAllReturnRoutesSendNodeInformationReplicationSendCreateButtonDeleteButton"

var _ControllerCommand_index = [...]uint16{0, 4, 13, 29, 49, 61, 77, 90, 107, 126, 146, 171, 188, 209, 228, 243, 255, 267}

func (i ControllerCommand) String() string {
	if i >= ControllerCommand(len(_ControllerCommand_index)-1) {
		return "ControllerCommand(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ControllerCommand_name[_ControllerCommand_index[i]:_ControllerCommand_index[i+1]]
}
