// Code generated by "stringer -trimprefix=ControllerState_ -type=ControllerState"; DO NOT EDIT.

package goopenzwave

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ControllerState_Normal-0]
	_ = x[ControllerState_Starting-1]
	_ = x[ControllerState_Cancel-2]
	_ = x[ControllerState_Error-3]
	_ = x[ControllerState_Waiting-4]
	_ = x[ControllerState_Sleeping-5]
	_ = x[ControllerState_InProgress-6]
	_ = x[ControllerState_Completed-7]
	_ = x[ControllerState_Failed-8]
	_ = x[ControllerState_NodeOK-9]
	_ = x[ControllerState_NodeFailed-10]
}

const _ControllerState_name = "NormalStartingCancelErrorWaitingSleepingInProgressCompletedFailedNodeOKNodeFailed"

var _ControllerState_index = [...]uint8{0, 6, 14, 20, 25, 32, 40, 50, 59, 65, 71, 81}

func (i ControllerState) String() string {
	if i >= ControllerState(len(_ControllerState_index)-1) {
		return "ControllerState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ControllerState_name[_ControllerState_index[i]:_ControllerState_index[i+1]]
}
