// Code generated by "stringer -trimprefix=ControllerError_ -type=ControllerError"; DO NOT EDIT.

package goopenzwave

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ControllerError_None-0]
	_ = x[ControllerError_ButtonNotFound-1]
	_ = x[ControllerError_NodeNotFound-2]
	_ = x[ControllerError_NotBridge-3]
	_ = x[ControllerError_NotSUC-4]
	_ = x[ControllerError_NotSecondary-5]
	_ = x[ControllerError_NotPrimary-6]
	_ = x[ControllerError_IsPrimary-7]
	_ = x[ControllerError_NotFound-8]
	_ = x[ControllerError_Busy-9]
	_ = x[ControllerError_Failed-10]
	_ = x[ControllerError_Disabled-11]
	_ = x[ControllerError_Overflow-12]
}

const _ControllerError_name = "NoneButtonNotFoundNodeNotFoundNotBridgeNotSUCNotSecondaryNotPrimaryIsPrimaryNotFoundBusyFailedDisabledOverflow"

var _ControllerError_index = [...]uint8{0, 4, 18, 30, 39, 45, 57, 67, 76, 84, 88, 94, 102, 110}

func (i ControllerError) String() string {
	if i >= ControllerError(len(_ControllerError_index)-1) {
		return "ControllerError(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ControllerError_name[_ControllerError_index[i]:_ControllerError_index[i+1]]
}
