// Code generated by "stringer -trimprefix=NotificationType_ -type=NotificationType"; DO NOT EDIT.

package goopenzwave

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NotificationType_ValueAdded-0]
	_ = x[NotificationType_ValueRemoved-1]
	_ = x[NotificationType_ValueChanged-2]
	_ = x[NotificationType_ValueRefreshed-3]
	_ = x[NotificationType_Group-4]
	_ = x[NotificationType_NodeNew-5]
	_ = x[NotificationType_NodeAdded-6]
	_ = x[NotificationType_NodeRemoved-7]
	_ = x[NotificationType_NodeProtocolInfo-8]
	_ = x[NotificationType_NodeNaming-9]
	_ = x[NotificationType_NodeEvent-10]
	_ = x[NotificationType_PollingDisabled-11]
	_ = x[NotificationType_PollingEnabled-12]
	_ = x[NotificationType_SceneEvent-13]
	_ = x[NotificationType_CreateButton-14]
	_ = x[NotificationType_DeleteButton-15]
	_ = x[NotificationType_ButtonOn-16]
	_ = x[NotificationType_ButtonOff-17]
	_ = x[NotificationType_DriverReady-18]
	_ = x[NotificationType_DriverFailed-19]
	_ = x[NotificationType_DriverReset-20]
	_ = x[NotificationType_EssentialNodeQueriesComplete-21]
	_ = x[NotificationType_NodeQueriesComplete-22]
	_ = x[NotificationType_AwakeNodesQueried-23]
	_ = x[NotificationType_AllNodesQueriedSomeDead-24]
	_ = x[NotificationType_AllNodesQueried-25]
	_ = x[NotificationType_Notification-26]
	_ = x[NotificationType_DriverRemoved-27]
	_ = x[NotificationType_ControllerCommand-28]
	_ = x[NotificationType_NodeReset-29]
	_ = x[NotificationType_UserAlerts-30]
	_ = x[NotificationType_ManufacturerSpecificDBReady-31]
}

const _NotificationType_name = "ValueAddedValueRemovedValueChangedValueRefreshedGroupNodeNewNodeAddedNodeRemovedNodeProtocolInfoNodeNamingNodeEventPollingDisabledPollingEnabledSceneEventCreateButtonDeleteButtonButtonOnButtonOffDriverReadyDriverFailedDriverResetEssentialNodeQueriesCompleteNodeQueriesCompleteAwakeNodesQueriedAllNodesQueriedSomeDeadAllNodesQueriedNotificationDriverRemovedControllerCommandNodeResetUserAlertsManufacturerSpecificDBReady"

var _NotificationType_index = [...]uint16{0, 10, 22, 34, 48, 53, 60, 69, 80, 96, 106, 115, 130, 144, 154, 166, 178, 186, 195, 206, 218, 229, 257, 276, 293, 316, 331, 343, 356, 373, 382, 392, 419}

func (i NotificationType) String() string {
	if i >= NotificationType(len(_NotificationType_index)-1) {
		return "NotificationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NotificationType_name[_NotificationType_index[i]:_NotificationType_index[i+1]]
}
