// Code generated by "stringer -trimprefix=NotificationCode_ -type=NotificationCode"; DO NOT EDIT.

package goopenzwave

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NotificationCode_MsgComplete-0]
	_ = x[NotificationCode_Timeout-1]
	_ = x[NotificationCode_NoOperation-2]
	_ = x[NotificationCode_Awake-3]
	_ = x[NotificationCode_Sleep-4]
	_ = x[NotificationCode_Dead-5]
	_ = x[NotificationCode_Alive-6]
}

const _NotificationCode_name = "MsgCompleteTimeoutNoOperationAwakeSleepDeadAlive"

var _NotificationCode_index = [...]uint8{0, 11, 18, 29, 34, 39, 43, 48}

func (i NotificationCode) String() string {
	if i >= NotificationCode(len(_NotificationCode_index)-1) {
		return "NotificationCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NotificationCode_name[_NotificationCode_index[i]:_NotificationCode_index[i+1]]
}
