// Code generated by "stringer -trimprefix=UserAlertNotification_ -type=UserAlertNotification"; DO NOT EDIT.

package goopenzwave

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UserAlertNotification_None-0]
	_ = x[UserAlertNotification_ConfigOutOfDate-1]
	_ = x[UserAlertNotification_MFSOutOfDate-2]
	_ = x[UserAlertNotification_ConfigFileDownloadFailed-3]
	_ = x[UserAlertNotification_DNSError-4]
	_ = x[UserAlertNotification_NodeReloadRequired-5]
	_ = x[UserAlertNotification_UnsupportedController-6]
	_ = x[UserAlertNotification_ApplicationStatus_Retry-7]
	_ = x[UserAlertNotification_ApplicationStatus_Queued-8]
	_ = x[UserAlertNotification_ApplicationStatus_Rejected-9]
}

const _UserAlertNotification_name = "NoneConfigOutOfDateMFSOutOfDateConfigFileDownloadFailedDNSErrorNodeReloadRequiredUnsupportedControllerApplicationStatus_RetryApplicationStatus_QueuedApplicationStatus_Rejected"

var _UserAlertNotification_index = [...]uint8{0, 4, 19, 31, 55, 63, 81, 102, 125, 149, 175}

func (i UserAlertNotification) String() string {
	if i >= UserAlertNotification(len(_UserAlertNotification_index)-1) {
		return "UserAlertNotification(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UserAlertNotification_name[_UserAlertNotification_index[i]:_UserAlertNotification_index[i+1]]
}
