// Code generated by "stringer -trimprefix=ValueType_ -type=ValueType"; DO NOT EDIT.

package goopenzwave

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ValueType_Bool-0]
	_ = x[ValueType_Byte-1]
	_ = x[ValueType_Decimal-2]
	_ = x[ValueType_Int-3]
	_ = x[ValueType_List-4]
	_ = x[ValueType_Schedule-5]
	_ = x[ValueType_Short-6]
	_ = x[ValueType_String-7]
	_ = x[ValueType_Button-8]
	_ = x[ValueType_Raw-9]
	_ = x[ValueType_BitSet-10]
}

const _ValueType_name = "BoolByteDecimalIntListScheduleShortStringButtonRawBitSet"

var _ValueType_index = [...]uint8{0, 4, 8, 15, 18, 22, 30, 35, 41, 47, 50, 56}

func (i ValueType) String() string {
	if i >= ValueType(len(_ValueType_index)-1) {
		return "ValueType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValueType_name[_ValueType_index[i]:_ValueType_index[i+1]]
}
