// Code generated by "stringer -trimprefix=ValueGenre_ -type=ValueGenre"; DO NOT EDIT.

package goopenzwave

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ValueGenre_Basic-0]
	_ = x[ValueGenre_User-1]
	_ = x[ValueGenre_Config-2]
	_ = x[ValueGenre_System-3]
}

const _ValueGenre_name = "BasicUserConfigSystem"

var _ValueGenre_index = [...]uint8{0, 5, 9, 15, 21}

func (i ValueGenre) String() string {
	if i >= ValueGenre(len(_ValueGenre_index)-1) {
		return "ValueGenre(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValueGenre_name[_ValueGenre_index[i]:_ValueGenre_index[i+1]]
}
